# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'Producthunt' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  #pod 'YNDropDownMenu'
  # Pods for Producthunt

  target 'ProducthuntTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProducthuntUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
